### ISSUE TITLE
Cannot select or upload VTT files

### ISSUE THREAD

**Issue by chris-steele** [adapt-security/adapt-authoring-middleware#5]
### What happened?
I imported a course with the standard example of the media component with its mp4 and VTT files. Both assets appear in the asset manager. If I create a new media component in the course and attempt to select the existing VTT file the message 'no assets found' it shown.

If I attempt to upload the standard example VTT file from the framework I get the following server error:

`TypeError: Cannot read properties of undefined (reading 'mime')`

### Steps to reproduce
See above

### Authoring tool version
master

**Comment by taylortom** [comment]
Should be fixed

**Comment by joe-allen-89** [comment]
Schema issue addressed within media component - https://github.com/adaptlearning/adapt-contrib-media/pull/282

**Comment by joe-allen-89** [comment]
The schema changes worked as expected, now able to select and upload vtt files through the media player.
